/* eslint-env es6 */

/* Module that reutilizes the autogenerated boilerplate for navigating between views */
sap.ui.define([], function () {
  return {
    constructor: function () {},
    navigate: function (controller, ev) {
      const actionParameters = JSON.parse(ev.getSource().data("wiring").replace(/'/g, "\""));
      const eventType = ev.getId();
      const aTargets = actionParameters[eventType].targets || [];
      aTargets.forEach(function (oTarget) {
        const oControl = controller.byId(oTarget.id);
        if (oControl) {
          const oParams = {};
          for (const prop in oTarget.parameters) {
            oParams[prop] = ev.getParameter(oTarget.parameters[prop]);
          }
          oControl[oTarget.action](oParams);
        }
      });
      const oNavigation = actionParameters[eventType].navigation;
      if (oNavigation) {
        const oParams = {};
        (oNavigation.keys || []).forEach(function (prop) {
          oParams[prop.name] = encodeURIComponent(JSON.stringify({
            value: ev.getSource().getBindingContext(oNavigation.model).getProperty(prop.name),
            type: prop.type
          }));
        });
        if (Object.getOwnPropertyNames(oParams).length !== 0) {
          controller.getOwnerComponent().getRouter().navTo(oNavigation.routeName, oParams);
        } else {
          controller.getOwnerComponent().getRouter().navTo(oNavigation.routeName);
        }
      }
    }
  };
});